FROM quay.io/wildfly/wildfly:latest

RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

COPY ejb-module/build/libs/organization-ejb.jar /opt/jboss/wildfly/standalone/deployments/
COPY web-module/build/libs/web-module.war /opt/jboss/wildfly/standalone/deployments/

COPY wildfly-config/configure-datasource.cli /opt/jboss/wildfly/

EXPOSE 8080 9990

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]